### ISSUE TITLE
Calcuating fees

### ISSUE THREAD

**Issue by pegahcarter** [marchowardbegins/crypto-arbitrage-bot#3]
Is there a reasonable way to dynamically locate the fees for each exchange?  I know some exchanges have a variable fee rate depending on how much volume you trade in a month.

**Comment by marchowardbegins** [comment]
I have yet to find an API that provides exchange fees so until this can be found this make be a bit manual.  Would it make sense to not include fees initially in the signal bot, just to get a feel for the which exchange the best arb opps are coming from, then go back and apply a fee table?  It seems fees in general are between .01 and .2 (many exceptions but this is for many of the more reputable exchanges). So for this initial bot we could hard-code in a .2% fee knowing that if there are any arb opps it would cost more more than this max fee?

So some thoughts on options here:

1. Hard-code a .2% just for testing the initial MVP. The bot could then search all exchanges.
2. Start with a list of the top 10 exchanges and create a table of fees. The bot would then only search these 10 exchanges.
3. Start with no fee, get a feel of which exchanges the best arg opps are coming from then go back and code in the respective fees.

For #1 and #3 we may want to consider a black list of exchanges taking into account less reputable exchanges or ones that have fake volume. Below is a list of the exchanges that we should only consider trading on based on a fake volume analysis:
https://www.blockchaintransparency.org/exchangerankings/

**Comment by pegahcarter** [comment]
@marchowardbegins that's a good idea to begin with a static maximum fee and work the way down from there.  I'd prefer to overestimate fees, and working our way down from there.  So the MVP will have a viable way to track what we think the max fees would be, without requiring us to go into too much depth for several exchanges.

**Comment by pegahcarter** [comment]
For clarity, I'll start with a 0.2% trading fee, like you recommended.
